version: "3.10"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=common:1:1

  producer:
    build:
      context: .
      dockerfile: Dockerfile.txt
    volumes:
      - C:/NUWEE/SECOND_TERM/TCS/Lab5/producer:/producer:rw
  consumer:
    build:
      context: .
      dockerfile: Dockerfile2.txt
    volumes:
      - C:/NUWEE/SECOND_TERM/TCS/Lab4/consumer:/consumer:rw
