FROM mcr.microsoft.com/windows/servercore:ltsc2016
RUN powershell -Command \
    $ErrorActionPreference = 'Stop'; \
    $TLS12 = [System.Security.Authentication.SslProtocols]::Tls12; \
    [System.Net.ServicePointManager]::SecurityProtocol = $TLS12; \
    Invoke-WebRequest -Method Get -Uri https://www.apachelounge.com/download/VS17/binaries/httpd-2.4.57-win64-VS17.zip -OutFile c:\httpd-2.4.57-win64-VS17.zip ; \
    Expand-Archive -Path c:\httpd.zip -DestinationPath C:\ ; \
    Move-Item C:\httpd-2.4.57-win64-VS17\Apache24 C:\Apache24 ; \
    Remove-Item C:\httpd-2.4.57-win64-VS17.zip ; \
    Remove-Item -Recurse -Force C:\httpd-2.4.57-win64-VS17
COPY web_server/ /Apache24/htdocs/
EXPOSE 80
CMD ["C:/Apache24/bin/httpd.exe", "-w"]